
project_id = "emxacynrmcnocumsbebb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"

[auth.redirect_urls]
allow_list = ["http://localhost:5173/auth/callback"]

[functions]
[functions.market-prices]
verify_jwt = false
