
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emxacynrmcnocumsbebb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVteGFjeW5ybWNub2N1bXNiZWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3Nzc3NzcsImV4cCI6MjA1NzM1Mzc3N30.QLvGpu50C1vVcu1kEpnEN5dWRikVqL4wMBxusmpkNp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
